all: lab5 lab52

lab5: lab5.c lab5.o
	gcc -g -o lab5 lab5.c lab5.o
lab5.o: lab5.s
	as -gstabs -o lab5.o lab5.s

lab52: lab52.c lab52.o
	gcc -g -o lab52 lab52.c lab52.o
lab52.o: lab52.s
	as -gstabs -o lab52.o lab52.s
	





